keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: passport-system
  resource: passport-system
  public-client: true
  security-constraints[0]:
    authRoles[0]: user
    securityCollections[0]:
      patterns[0]: /login/*

server:
  port: 8081

spring:
  freemarker:
#    request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点